In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [8]:
b = np.array([[1,2,3],[4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
a.shape

(3,)

In [12]:
a

array([1, 2, 3])

In [13]:
b.dtype

dtype('int32')

In [14]:
b.ndim

2

In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
print(type(b))

<class 'numpy.ndarray'>


In [17]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
c = range(10000)

In [19]:
%timeit [i**3 for i in c]

5.2 ms ± 97 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
c_numpy = np.arange(10000)

In [21]:
%timeit c_numpy**3

34.1 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [25]:
%timeit list(map(lambda x,y : x*y, l1, l2))

2.82 ms ± 53 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
a1 = np.array(l1)
a2 = np.array(l2)

In [27]:
%timeit a1*a2 

12.9 µs ± 399 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [32]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
%timeit np.ones((3,2))*3

5.77 µs ± 438 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
%timeit np.full((3,3), 2)

4.05 µs ± 258 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
np.full((3,3), 2.2, dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [40]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [41]:
v = np.array([1,2,3])

In [42]:
v

array([1, 2, 3])

In [43]:
np.tile(v, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
np.tile(v, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [46]:
# random value 
np.random.random()

0.9464901964937801

In [55]:
50*np.random.random()+2 # return a random value from 2 to 52

27.597553155917087

In [56]:
# matrix with random value
np.random.random([3,3])

array([[0.80314722, 0.30420237, 0.30188201],
       [0.7025869 , 0.33624996, 0.65267147],
       [0.50851976, 0.96442986, 0.49505687]])

In [60]:
np.random.random([3,3])

array([[0.00149034, 0.52583901, 0.35836897],
       [0.20539877, 0.56657805, 0.11893637],
       [0.52247756, 0.16934192, 0.17530415]])

In [63]:
# geting equally spaced value from numpy
a = np.linspace(1, 50, 100)

In [64]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [66]:
a.itemsize

8

In [68]:
b = np.arange(18).reshape(2, 3, 3)

In [69]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [70]:
b.shape

(2, 3, 3)

In [71]:
# to automatically adjust the dimension accordingly we have to pass numpy -1 on the third argument
np.arange(18).reshape(2, 3, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [72]:
a = np.arange(2, 18, 2)

In [73]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [74]:
a[0]

2

In [75]:
a[2]

6

In [76]:
a[2,4,6]

IndexError: too many indices for array

In [77]:
# we need to bundled the argument
a[[2,4,6]]

array([ 6, 10, 14])

In [78]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [79]:
a[2:5]

array([ 6,  8, 10])

In [83]:
# hop over 2 value and then again hop till the end
a[0::2]

array([ 2,  6, 10, 14])

In [84]:
a[::2]

array([ 2,  6, 10, 14])

In [88]:
a = np.arange(1,10).reshape(3,3)

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
a[2,2]

9

In [91]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [92]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b = a

In [95]:
b[0,0] = 11

In [96]:
b

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [97]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [98]:
np.shares_memory(a,b)

True

In [99]:
# to create sepearte object of a
b = a.copy()

In [100]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [101]:
b

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [102]:
b[0,0] = 0

In [103]:
b

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [105]:
np.shares_memory(a,b)

False

In [106]:
a = np.array([[1,2,3],[4,5,6]])

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# transpose make all my row as column and vice versa
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [109]:
b = np.array([[7,8,9], [10,11,12]])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [112]:
a == b

array([[False, False, False],
       [False, False, False]])

In [114]:
# vertically stacking array
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [118]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [119]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [120]:
np.sum(a)

21

In [121]:
np.median(a)

3.5

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.std(a)

1.707825127659933

In [125]:
a = np.arange(1, 10).reshape(3,3)

In [126]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
np.linalg.det(a)

6.66133814775094e-16

In [132]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [133]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [135]:
b = a.T

In [136]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [138]:
np.dot(a, b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [139]:
a = np.array([1, 1, 0], dtype = bool)
b = np.array([1, 0, 1], dtype = bool)

In [140]:
np.logical_or(a, b)

array([ True,  True,  True])

In [141]:
np.logical_and(a, b)

array([ True, False, False])

In [142]:
a == a

array([ True,  True,  True])

In [146]:
a == a

array([ True,  True,  True])

In [145]:
np.all(a == a)

True

In [147]:
a = np.array([[1, 2],[3,4]])

In [148]:
a

array([[1, 2],
       [3, 4]])

In [149]:
np.sum(a)

10

In [151]:
# for calculating row sum
a.sum(axis = 0)

array([4, 6])

In [152]:
# for calculating column sum
a.sum(axis = 1)

array([3, 7])

In [153]:
a.max()

4

In [154]:
a.argmax()

3

In [155]:
a

array([[1, 2],
       [3, 4]])

In [156]:
a.shape

(2, 2)

In [157]:
a = np.arange(1, 10)

In [158]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
a.shape

(9,)

In [160]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [161]:
a[:, np.newaxis].shape

(9, 1)

In [162]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])